
/**
* HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* dimanche 14 novembre 2021 14 h 50 GMT+01:00
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
